"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import ArticleHeader from "@/components/ArticleHeader";

interface Lead {
  id: number;
  text: string;
}

interface FactItem {
  id: number;
  text: string;
  source: string;
}

interface VerifyItem {
  id: number;
  text: string;
  checked: boolean;
}

interface ReviewerSuggestion {
  id: number;
  text: string;
  checked: boolean;
  showDetails?: boolean;
}

interface ArticleDraft {
  id: string;
  created_at: string;
  article_lead: string | null;
  // topic과 article_type은 실제 테이블에 없을 수 있음
  topic?: string | null;
  article_type?: string | null;
}

export default function ArticlesPage() {
  const searchParams = useSearchParams();
  const supabase = createClient();
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [articleType, setArticleType] = useState("스트린이드");
  const [drafts, setDrafts] = useState<ArticleDraft[]>([]);
  const [loadingDrafts, setLoadingDrafts] = useState(false);
  const [showDraftsList, setShowDraftsList] = useState(false);
  const hasAutoGenerated = useRef(false); // 자동 생성 여부 추적

  // URL 쿼리 파라미터에서 주제 가져오기
  useEffect(() => {
    const topicParam = searchParams.get("topic");
    if (topicParam) {
      const decodedTopic = decodeURIComponent(topicParam);
      setTopic(decodedTopic);
      // 자동 생성 플래그 설정 (topic 상태 변경 시 자동 생성)
      hasAutoGenerated.current = true;
    } else {
      // topic이 없으면 자동 생성 플래그 리셋
      hasAutoGenerated.current = false;
    }
  }, [searchParams]);

  // 초안 목록 불러오기 (모든 사용자의 최신 초안)
  const loadDrafts = async (autoLoadLatest: boolean = false) => {
    setLoadingDrafts(true);
    try {
      // user_id 필터링 없이 모든 사용자의 최신 초안 가져오기
      const { data, error } = await supabase
        .from("article_drafts")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(20);

      if (error) {
        console.error("Supabase query error:", error);
        console.error("Error details:", {
          message: error.message,
          code: error.code,
          details: error.details,
          hint: error.hint,
        });
        throw error;
      }

      console.log("Loaded drafts:", data?.length || 0);
      setDrafts(data || []);

      // 가장 최신 초안을 자동으로 화면에 불러오기 (옵션)
      if (autoLoadLatest && data && data.length > 0) {
        const latestDraft = data[0];
        await loadDraftData(latestDraft);
      }
    } catch (error: any) {
      console.error("Error loading drafts:", error);
      console.error("Error type:", typeof error);
      console.error("Error keys:", Object.keys(error || {}));
      if (error?.message) {
        console.error("Error message:", error.message);
      }
      // 에러가 발생해도 빈 배열로 설정하여 UI가 깨지지 않도록
      setDrafts([]);
    } finally {
      setLoadingDrafts(false);
    }
  };

  // 초안 데이터를 화면에 표시하는 함수 (loadDraft와 동일한 로직)
  const loadDraftData = async (data: any) => {
    try {
      // 주제 설정
      if (data.topic) {
        setTopic(data.topic);
      }

      // 리드 설정
      if (data.leads && Array.isArray(data.leads)) {
        setLeads(
          data.leads.map((lead: any, index: number) => ({
            id: index + 1,
            text: typeof lead === "string" ? lead : lead.text || lead,
          }))
        );
      }

      // 팩트 설정
      if (data.facts && Array.isArray(data.facts)) {
        setFacts(
          data.facts.map((fact: any, index: number) => ({
            id: index + 1,
            text: typeof fact === "string" ? fact : fact.text || fact,
            source: typeof fact === "object" ? fact.source || "출처" : "출처",
          }))
        );
      }

      // 분석 설정
      if (data.analysis) {
        setAnalysis(data.analysis);
      }

      // 검증 리스트 설정
      if (data.verify_list && Array.isArray(data.verify_list)) {
        setVerifyList(
          data.verify_list.map((item: any, index: number) => ({
            id: index + 1,
            text: typeof item === "string" ? item : item.text || item,
            checked: typeof item === "object" ? item.checked || false : false,
          }))
        );
      }

      // 제안 설정
      if (data.suggestions && Array.isArray(data.suggestions)) {
        setSuggestions(
          data.suggestions.map((item: any, index: number) => ({
            id: index + 1,
            text: typeof item === "string" ? item : item.text || item,
            checked: typeof item === "object" ? item.checked || false : false,
          }))
        );
      }

      // 기사 내용 설정
      setArticleContent({
        lead: data.article_lead || "",
        body: data.article_body || "",
      });
    } catch (error) {
      console.error("Error loading draft data:", error);
    }
  };

  // 초안 불러오기 (ID로 조회)
  const loadDraft = async (draftId: string) => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from("article_drafts")
        .select("*")
        .eq("id", draftId)
        .single();

      if (error) throw error;

      if (data) {
        await loadDraftData(data);
        setShowDraftsList(false);
      }
    } catch (error) {
      console.error("Error loading draft:", error);
      alert("초안을 불러오는데 실패했습니다.");
    } finally {
      setLoading(false);
    }
  };

  // 컴포넌트 마운트 시 초안 목록만 불러오기 (자동 로드 안 함)
  useEffect(() => {
    loadDrafts(false); // 이전 내용 자동 로드 비활성화
  }, []);
  
  // 리드 10개
  const [leads, setLeads] = useState<Lead[]>([]);
  
  // FACT BOX
  const [facts, setFacts] = useState<FactItem[]>([]);
  
  // ANALYSIS
  const [analysis, setAnalysis] = useState("");
  
  // VERIFY LIST
  const [verifyList, setVerifyList] = useState<VerifyItem[]>([]);
  
  // Reviewer 제안
  const [suggestions, setSuggestions] = useState<ReviewerSuggestion[]>([]);
  
  // 기사 내용
  const [articleContent, setArticleContent] = useState({
    lead: "",
    body: "",
  });

  const handleGenerateDraft = useCallback(async () => {
    const currentTopic = topic.trim();
    if (!currentTopic) {
      alert("기사 주제를 입력해주세요.");
      return;
    }

    // 이미 로딩 중이면 중복 요청 방지
    if (loading) {
      return;
    }

    setLoading(true);
    
    // 기존 데이터 초기화 (새 초안 생성 중임을 명확히 표시)
    setLeads([]);
    setFacts([]);
    setAnalysis("");
    setVerifyList([]);
    setSuggestions([]);
    setArticleContent({ lead: "", body: "" });

    try {
      // n8n Webhook을 통해 AI로 리드 생성
      const response = await fetch("/api/generate-leads", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          topic: currentTopic,
          articleType,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "리드 생성에 실패했습니다.");
      }

      const data = await response.json();

      // 리드 10개 설정
      if (data.leads && Array.isArray(data.leads)) {
        setLeads(
          data.leads.map((lead: string, index: number) => ({
            id: index + 1,
            text: lead,
          }))
        );
      }

      // FACT BOX 설정
      if (data.facts && Array.isArray(data.facts)) {
        setFacts(
          data.facts.map((fact: any, index: number) => ({
            id: index + 1,
            text: fact.text || fact,
            source: fact.source || "출처",
          }))
        );
      }

      // ANALYSIS 설정
      if (data.analysis) {
        setAnalysis(data.analysis);
      }

      // VERIFY LIST 설정
      if (data.verifyList && Array.isArray(data.verifyList)) {
        setVerifyList(
          data.verifyList.map((item: any, index: number) => ({
            id: index + 1,
            text: typeof item === "string" ? item : item.text,
            checked: typeof item === "object" ? item.checked || false : false,
          }))
        );
      }

      // 기사 초안 기본값 설정
      if (data.leads && data.leads.length > 0) {
        setArticleContent({
          lead: data.leads[0] || `${currentTopic}에 대한 기사 리드입니다.`,
          body: data.analysis || `${currentTopic}의 본문 내용이 여기에 들어갑니다.`,
        });
      }

      // Supabase에 초안 저장
      try {
        const {
          data: { user },
        } = await supabase.auth.getUser();

        if (user) {
          await supabase.from("article_drafts").insert({
            user_id: user.id,
            topic: currentTopic,
            article_type: articleType,
            success: true,
            leads: data.leads || [],
            facts: data.facts || [],
            analysis: data.analysis || "",
            verify_list: data.verifyList || [],
            suggestions: data.suggestions || [],
            article_lead: data.leads?.[0] || "",
            article_body: data.analysis || "",
          });

          // 초안 목록 새로고침 (자동 로드하지 않음 - 이미 화면에 표시됨)
          loadDrafts(false);
        }
      } catch (saveError) {
        console.error("Error saving draft:", saveError);
        // 저장 실패해도 계속 진행
      }
    } catch (error: any) {
      console.error("Error generating draft:", error);
      alert(error.message || "리드 생성에 실패했습니다. 다시 시도해주세요.");
      
      // 에러 발생 시 기본값 설정
      setLeads([
        { id: 1, text: `${currentTopic}에 대한 첫 번째 리드 제안입니다.` },
        { id: 2, text: `${currentTopic}의 핵심 내용을 다루는 두 번째 리드입니다.` },
      ]);
    } finally {
      setLoading(false);
    }
  }, [topic, articleType, loading, supabase, loadDrafts]);

  // topic이 URL에서 설정되고 자동 생성 플래그가 있으면 자동으로 초안 생성
  useEffect(() => {
    if (topic.trim() && hasAutoGenerated.current) {
      hasAutoGenerated.current = false; // 한 번만 실행
      // 약간의 지연을 두어 상태 업데이트가 완료된 후 실행
      const timer = setTimeout(() => {
        handleGenerateDraft();
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [topic, handleGenerateDraft]);

  const toggleVerifyItem = (id: number) => {
    setVerifyList((prev) =>
      prev.map((item) =>
        item.id === id ? { ...item, checked: !item.checked } : item
      )
    );
  };

  const toggleSuggestion = (id: number) => {
    setSuggestions((prev) =>
      prev.map((item) =>
        item.id === id ? { ...item, checked: !item.checked } : item
      )
    );
  };

  const toggleSuggestionDetails = (id: number) => {
    setSuggestions((prev) =>
      prev.map((item) =>
        item.id === id
          ? { ...item, showDetails: !item.showDetails }
          : item
      )
    );
  };

  return (
    <div className="flex h-screen flex-col bg-gray-50">
      <ArticleHeader
        onShowDrafts={() => setShowDraftsList(!showDraftsList)}
        draftsCount={drafts.length}
      />

      {/* 초안 목록 모달 */}
      {showDraftsList && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="w-full max-w-2xl rounded-lg bg-white shadow-xl">
            <div className="flex items-center justify-between border-b border-gray-200 p-4">
              <h2 className="text-lg font-semibold text-gray-900">저장된 초안</h2>
              <button
                onClick={() => setShowDraftsList(false)}
                className="rounded-md p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
              >
                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="max-h-96 overflow-y-auto p-4">
              {loadingDrafts ? (
                <div className="py-8 text-center text-gray-500">로딩 중...</div>
              ) : drafts.length === 0 ? (
                <div className="py-8 text-center text-gray-500">저장된 초안이 없습니다.</div>
              ) : (
                <div className="space-y-2">
                  {drafts.map((draft) => (
                    <div
                      key={draft.id}
                      onClick={() => loadDraft(draft.id)}
                      className="cursor-pointer rounded-lg border border-gray-200 p-4 hover:bg-gray-50"
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <h3 className="font-medium text-gray-900">
                            {draft.topic || draft.article_lead?.substring(0, 50) || "제목 없음"}
                          </h3>
                          {draft.article_lead && (
                            <p className="mt-1 text-sm text-gray-600 line-clamp-2">
                              {draft.article_lead}
                            </p>
                          )}
                          <p className="mt-2 text-xs text-gray-500">
                            {new Date(draft.created_at).toLocaleString("ko-KR")}
                          </p>
                        </div>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            loadDraft(draft.id);
                          }}
                          className="ml-4 rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700"
                        >
                          불러오기
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            <div className="border-t border-gray-200 p-4">
              <button
                onClick={() => loadDrafts(true)}
                disabled={loadingDrafts}
                className="w-full rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"
              >
                {loadingDrafts ? "새로고침 중..." : "새로고침"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 로딩 오버레이 */}
      {loading && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="rounded-lg bg-white p-8 shadow-xl">
            <div className="flex flex-col items-center gap-4">
              <svg className="h-12 w-12 animate-spin text-blue-600" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <div className="text-center">
                <p className="text-lg font-semibold text-gray-900">AI가 초안을 생성하고 있습니다</p>
                <p className="mt-2 text-sm text-gray-600">
                  주제: <span className="font-medium">{topic}</span>
                </p>
                <p className="mt-1 text-xs text-gray-500">잠시만 기다려주세요...</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 메인 컨텐츠 */}
      <div className="flex flex-1 overflow-hidden">
        {/* 왼쪽 패널: 리드 10개 */}
        <div className="w-80 border-r border-gray-200 bg-white p-4 overflow-y-auto">
          <h2 className="mb-4 text-sm font-semibold text-gray-900">
            리드 10개 자동 생성
          </h2>
          <div className="space-y-2">
            {loading ? (
              <div className="py-8 text-center">
                <div className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-blue-600 border-t-transparent"></div>
                <p className="mt-2 text-sm text-gray-500">초안 생성 중...</p>
              </div>
            ) : leads.length === 0 ? (
              <p className="text-sm text-gray-500">
                초안을 생성하면 리드가 표시됩니다.
              </p>
            ) : (
              leads.map((lead) => (
                <div
                  key={lead.id}
                  className="cursor-pointer rounded border border-gray-200 p-3 text-sm hover:bg-gray-50"
                  onClick={() => setArticleContent({ ...articleContent, lead: lead.text })}
                >
                  <span className="font-medium text-gray-700">{lead.id}.</span>{" "}
                  {lead.text}
                </div>
              ))
            )}
          </div>
        </div>

        {/* 중앙 컨텐츠 영역 */}
        <div className="flex flex-1 flex-col overflow-hidden">
          {/* 기사 주제 입력 */}
          <div className="border-b border-gray-200 bg-white p-4">
            <div className="flex items-center gap-4">
              <label className="text-sm font-medium text-gray-700">
                기사 주제 입력
              </label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="기사 주제를 입력하세요"
                disabled={loading}
                className="flex-1 rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 disabled:bg-gray-100 disabled:cursor-not-allowed"
                onKeyPress={(e) => {
                  if (e.key === "Enter" && !loading) {
                    handleGenerateDraft();
                  }
                }}
              />
              <button
                onClick={handleGenerateDraft}
                disabled={loading}
                className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed min-w-[120px]"
              >
                {loading ? (
                  <span className="flex items-center gap-2">
                    <svg className="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    생성 중...
                  </span>
                ) : (
                  "초안 생성 >"
                )}
              </button>
            </div>
          </div>

          {/* 기사 내용 영역 */}
          <div className="flex flex-1 overflow-hidden">
            {/* FACT BOX & ANALYSIS */}
            <div className="flex w-1/2 flex-col border-r border-gray-200">
              {/* FACT BOX */}
              <div className="flex-1 overflow-y-auto border-b border-gray-200 bg-white p-4">
                <h3 className="mb-3 text-sm font-semibold text-gray-900">
                  FACT BOX
                </h3>
                {facts.length === 0 ? (
                  <p className="text-sm text-gray-500">팩트가 없습니다.</p>
                ) : (
                  <ul className="space-y-2">
                    {facts.map((fact) => (
                      <li
                        key={fact.id}
                        className="flex items-start gap-2 text-sm text-gray-700"
                      >
                        <span className="text-blue-600">•</span>
                        <span className="flex-1">{fact.text}</span>
                        <span className="text-xs text-gray-500">
                          (출처: {fact.source})
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {/* ANALYSIS */}
              <div className="flex-1 overflow-y-auto bg-white p-4">
                <h3 className="mb-3 text-sm font-semibold text-gray-900">
                  ANALYSIS
                </h3>
                {analysis ? (
                  <p className="text-sm leading-relaxed text-gray-700">
                    {analysis}
                  </p>
                ) : (
                  <p className="text-sm text-gray-500">분석 내용이 없습니다.</p>
                )}
              </div>
            </div>

            {/* VERIFY LIST & 기사 본문 */}
            <div className="flex w-1/2 flex-col">
              {/* VERIFY LIST */}
              <div className="flex-1 overflow-y-auto border-b border-gray-200 bg-white p-4">
                <h3 className="mb-3 text-sm font-semibold text-gray-900">
                  VERIFY LIST
                </h3>
                {verifyList.length === 0 ? (
                  <p className="text-sm text-gray-500">검증 항목이 없습니다.</p>
                ) : (
                  <div className="space-y-2">
                    {verifyList.map((item) => (
                      <label
                        key={item.id}
                        className="flex cursor-pointer items-start gap-2 text-sm"
                      >
                        <input
                          type="checkbox"
                          checked={item.checked}
                          onChange={() => toggleVerifyItem(item.id)}
                          className="mt-1 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                        />
                        <span
                          className={item.checked ? "text-gray-700" : "text-gray-400"}
                        >
                          {item.text}
                        </span>
                      </label>
                    ))}
                  </div>
                )}
              </div>

              {/* 기사 본문 */}
              <div className="flex-1 overflow-y-auto bg-white p-4">
                <h3 className="mb-3 text-sm font-semibold text-gray-900">
                  기사 초안
                </h3>
                <div className="space-y-4">
                  <div>
                    <label className="mb-1 block text-xs font-medium text-gray-700">
                      리드
                    </label>
                    <textarea
                      value={articleContent.lead}
                      onChange={(e) =>
                        setArticleContent({ ...articleContent, lead: e.target.value })
                      }
                      className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                      rows={3}
                      placeholder="리드를 입력하세요"
                    />
                  </div>
                  <div>
                    <label className="mb-1 block text-xs font-medium text-gray-700">
                      본문
                    </label>
                    <textarea
                      value={articleContent.body}
                      onChange={(e) =>
                        setArticleContent({ ...articleContent, body: e.target.value })
                      }
                      className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:outline-none focus:ring-1 focus:ring-blue-500"
                      rows={10}
                      placeholder="본문을 입력하세요"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Reviewer 모드: 수정 제안 */}
      {suggestions.length > 0 && (
        <div className="border-t border-gray-200 bg-white p-4">
          <h3 className="mb-3 text-sm font-semibold text-gray-900">
            판겁자 묘드: 수정 제안
          </h3>
          <div className="space-y-2">
            {suggestions.map((suggestion) => (
              <div key={suggestion.id} className="flex items-start gap-2">
                <input
                  type="checkbox"
                  checked={suggestion.checked}
                  onChange={() => toggleSuggestion(suggestion.id)}
                  className="mt-1 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <span
                      className={`text-sm ${
                        suggestion.checked ? "text-gray-700" : "text-gray-400"
                      }`}
                    >
                      {suggestion.text}
                    </span>
                    {suggestion.id === 1 && (
                      <button
                        onClick={() => toggleSuggestionDetails(suggestion.id)}
                        className="text-xs text-blue-600 hover:text-blue-800"
                      >
                        {suggestion.showDetails ? "[수정 제안 숨기기]" : "[수정 제안 보기]"}
                      </button>
                    )}
                  </div>
                  {suggestion.showDetails && suggestion.id === 1 && (
                    <div className="mt-2 rounded-md bg-gray-50 p-2 text-xs text-gray-600">
                      수정된 전문적인 문장 예시가 여기에 표시됩니다.
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 하단 버튼 */}
      <div className="border-t border-gray-200 bg-white p-4">
        <div className="flex justify-end gap-3">
          <button className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
            초안 저장
          </button>
          <button className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
            다운로드
          </button>
          <button className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700">
            출고
          </button>
        </div>
      </div>
    </div>
  );
}
